name: ik_pharma
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_data_connect: ^0.2.1+2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^7.2.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - assets/images/
